package com.ruite.app.pet.translator

import android.content.Context
import com.ruite.app.pet.translator.entity.Index1Entity
import com.ruite.app.pet.translator.entity.LanguageEntity


object Const {

    val languageList = listOf(
        LanguageEntity("Portuguese", R.drawable.ic_portugal),
        LanguageEntity("China", R.drawable.ic_china),
        LanguageEntity("English", R.drawable.ic_english),
        LanguageEntity("Hindi", R.drawable.ic_hindi),
        LanguageEntity("Spanish", R.drawable.ic_spanish),
        LanguageEntity("French", R.drawable.ic_france),
    )

    fun dogSoundList(context: Context) = listOf(
        Index1Entity(context.getString(R.string.dog_sound_1), R.mipmap.ic_dog_curious, R.raw.dog_curious_sniff),
        Index1Entity(context.getString(R.string.dog_sound_2), R.mipmap.ic_dog_let_play, R.raw.dog_playful_chirping),
        Index1Entity(context.getString(R.string.dog_sound_3), R.mipmap.ic_dog_angry, R.raw.dog_angry),
        Index1Entity(context.getString(R.string.dog_sound_4), R.mipmap.ic_dog_friendly, R.raw.dog_friendly_greet),
        Index1Entity(context.getString(R.string.dog_sound_5), R.mipmap.ic_dog_happy, R.raw.dog_happy),
        Index1Entity(context.getString(R.string.dog_sound_6), R.mipmap.ic_dog_cry, R.raw.dog_cry),
        Index1Entity(context.getString(R.string.dog_sound_7), R.mipmap.ic_dog_agree, R.raw.dog_agree),
        Index1Entity(context.getString(R.string.dog_sound_8), R.mipmap.ic_dog_begging, R.raw.dog_begging),
        Index1Entity(context.getString(R.string.dog_sound_9), R.mipmap.ic_dog_cry_lying, R.raw.dog_cry_lying),
        Index1Entity(context.getString(R.string.dog_sound_10), R.mipmap.ic_dog_dance, R.raw.dog_dance),
        Index1Entity(context.getString(R.string.dog_sound_11), R.mipmap.ic_dog_exhauted, R.raw.dog_exhausted),
        Index1Entity(context.getString(R.string.dog_sound_12), R.mipmap.ic_dog_hand_clap, R.raw.dog_handclap),
        Index1Entity(context.getString(R.string.dog_sound_13), R.mipmap.ic_dog_happy_cry, R.raw.dog_happy_cry),
        Index1Entity(context.getString(R.string.dog_sound_14), R.mipmap.ic_dog_happy_walk, R.raw.dog_happy_walk),
        Index1Entity(context.getString(R.string.dog_sound_15), R.mipmap.ic_dog_hi_fence, R.raw.dog_hi_fence),
        Index1Entity(context.getString(R.string.dog_sound_16), R.mipmap.ic_dog_hi, R.raw.dog_hi),
        Index1Entity(context.getString(R.string.dog_sound_17), R.mipmap.ic_dog_lie, R.raw.dog_lie),
        Index1Entity(context.getString(R.string.dog_sound_18), R.mipmap.ic_dog_love, R.raw.dog_love),
        Index1Entity(context.getString(R.string.dog_sound_19), R.mipmap.ic_dog_no, R.raw.dog_no),
        Index1Entity(context.getString(R.string.dog_sound_20), R.mipmap.ic_dog_pet, R.raw.dog_pet),
        Index1Entity(context.getString(R.string.dog_sound_21), R.mipmap.ic_dog_raise_hand, R.raw.dog_raise_hand),
        Index1Entity(context.getString(R.string.dog_sound_22), R.mipmap.ic_dog_sad, R.raw.dog_sad),
        Index1Entity(context.getString(R.string.dog_sound_23), R.mipmap.ic_dog_scratch, R.raw.dog_scratch),
        Index1Entity(context.getString(R.string.dog_sound_24), R.mipmap.ic_dog_shy, R.raw.dog_shy),
        Index1Entity(context.getString(R.string.dog_sound_25), R.mipmap.ic_dog_soft_angry, R.raw.dog_soft_angry),
        Index1Entity(context.getString(R.string.dog_sound_26), R.mipmap.ic_dog_soft_begging, R.raw.dog_soft_begging),
        Index1Entity(context.getString(R.string.dog_sound_27), R.mipmap.ic_dog_startle, R.raw.dog_startle),
        Index1Entity(context.getString(R.string.dog_sound_28), R.mipmap.ic_dog_super_angry, R.raw.dog_super_angry),
        Index1Entity(context.getString(R.string.dog_sound_29), R.mipmap.ic_dog_wonder, R.raw.dog_wonder),
        Index1Entity(context.getString(R.string.dog_sound_30), R.mipmap.ic_dog_wow, R.raw.dog_wow),
        Index1Entity(context.getString(R.string.dog_sound_31), R.mipmap.ic_dog_yeah, R.raw.dog_yeah),
        Index1Entity(context.getString(R.string.dog_sound_32), R.mipmap.ic_dog_yes, R.raw.dog_yes),
        Index1Entity(context.getString(R.string.dog_sound_33), R.mipmap.ic_dog_adoring_chatter, R.raw.dog_adoring_chatter),
        Index1Entity(context.getString(R.string.dog_sound_34), R.mipmap.ic_dog_affectionate_barking, R.raw.dog_affectionate_barking),
        Index1Entity(context.getString(R.string.dog_sound_35), R.mipmap.ic_dog_affectionate_howl, R.raw.dog_affectionate_howl),
        Index1Entity(context.getString(R.string.dog_sound_36), R.mipmap.ic_dog_affectionate_lick, R.raw.dog_affectionate_lick),
        Index1Entity(context.getString(R.string.dog_sound_37), R.mipmap.ic_dog_affectionate_neigh, R.raw.dog_affectionate_neigh),
        Index1Entity(context.getString(R.string.dog_sound_38), R.mipmap.ic_dog_affectionate_nuzzle, R.raw.dog_affectionate_nuzzle),
        Index1Entity(context.getString(R.string.dog_sound_39), R.mipmap.ic_dog_alert_bark, R.raw.dog_alert_bark),
        Index1Entity(context.getString(R.string.dog_sound_40), R.mipmap.ic_dog_amused_honking, R.raw.dog_amused_honking),
        Index1Entity(context.getString(R.string.dog_sound_41), R.mipmap.ic_dog_amused_roaring, R.raw.dog_amused_roaring),
        Index1Entity(context.getString(R.string.dog_sound_42), R.mipmap.ic_dog_amused_squeak, R.raw.dog_amused_squeak),
        Index1Entity(context.getString(R.string.dog_sound_43), R.mipmap.ic_dog_anxious_howl, R.raw.dog_anxious_howl),
        Index1Entity(context.getString(R.string.dog_sound_44), R.mipmap.ic_dog_blissful_chatter, R.raw.dog_blissful_chatter),
        Index1Entity(context.getString(R.string.dog_sound_45), R.mipmap.ic_dog_blissful_gobbling, R.raw.dog_blissful_gobbling),
        Index1Entity(context.getString(R.string.dog_sound_46), R.mipmap.ic_dog_blissful_roar, R.raw.dog_blissful_roar),
        Index1Entity(context.getString(R.string.dog_sound_47), R.mipmap.ic_dog_cautious_growl, R.raw.dog_cautious_growl),
        Index1Entity(context.getString(R.string.dog_sound_48), R.mipmap.ic_dog_cheerful_growl, R.raw.dog_cheerful_growl),
        Index1Entity(context.getString(R.string.dog_sound_49), R.mipmap.ic_dog_cheerful_quacking, R.raw.dog_cheerful_quacking),
        Index1Entity(context.getString(R.string.dog_sound_50), R.mipmap.ic_dog_confused_yelp, R.raw.dog_confused_yelp),
        Index1Entity(context.getString(R.string.dog_sound_51), R.mipmap.ic_dog_contented_cluck, R.raw.dog_contented_cluck),
        Index1Entity(context.getString(R.string.dog_sound_52), R.mipmap.ic_dog_contented_ruff, R.raw.dog_contented_ruff),
        Index1Entity(context.getString(R.string.dog_sound_53), R.mipmap.ic_dog_curious_sniff, R.raw.dog_curious_sniff),
        Index1Entity(context.getString(R.string.dog_sound_54), R.mipmap.ic_dog_delighted_trilling, R.raw.dog_delighted_trilling),
        Index1Entity(context.getString(R.string.dog_sound_55), R.mipmap.ic_dog_delighted_whisted, R.raw.dog_delighted_whistle),
        Index1Entity(context.getString(R.string.dog_sound_56), R.mipmap.ic_dog_delighted_yelp, R.raw.dog_delighted_yelp),
        Index1Entity(context.getString(R.string.dog_sound_57), R.mipmap.ic_dog_eager_pant, R.raw.dog_eager_pant),
        Index1Entity(context.getString(R.string.dog_sound_58), R.mipmap.ic_dog_eager_whine, R.raw.dog_eager_whine),
        Index1Entity(context.getString(R.string.dog_sound_59), R.mipmap.ic_dog_ecstatic_barking, R.raw.dog_ecstatic_barking),
        Index1Entity(context.getString(R.string.dog_sound_60), R.mipmap.ic_dog_ecstatic_peep, R.raw.dog_ecstatic_peep),
        Index1Entity(context.getString(R.string.dog_sound_61), R.mipmap.ic_dog_elated_snuffing, R.raw.dog_elated_snuffling),
        Index1Entity(context.getString(R.string.dog_sound_62), R.mipmap.ic_dog_elated_trill, R.raw.dog_elated_trill),
        Index1Entity(context.getString(R.string.dog_sound_63), R.mipmap.ic_dog_euphoric_crooning, R.raw.dog_euphoric_crooning),
        Index1Entity(context.getString(R.string.dog_sound_64), R.mipmap.ic_dog_excitable_crowing, R.raw.dog_excitable_crowing),
        Index1Entity(context.getString(R.string.dog_sound_65), R.mipmap.ic_dog_excitable_chase, R.raw.dog_excited_chase),
        Index1Entity(context.getString(R.string.dog_sound_66), R.mipmap.ic_dog_excited_chirp, R.raw.dog_excited_chirp),
        Index1Entity(context.getString(R.string.dog_sound_67), R.mipmap.ic_dog_excited_woof, R.raw.dog_excited_woof),
        Index1Entity(context.getString(R.string.dog_sound_68), R.mipmap.ic_dog_friendly_greet, R.raw.dog_friendly_greet),
        Index1Entity(context.getString(R.string.dog_sound_69), R.mipmap.ic_dog_frightened_whine, R.raw.dog_frightened_whine),
        Index1Entity(context.getString(R.string.dog_sound_70), R.mipmap.ic_dog_gleeful_coo, R.raw.dog_gleeful_coo),
        Index1Entity(context.getString(R.string.dog_sound_71), R.mipmap.ic_dog_gleeful_squealing, R.raw.dog_gleeful_squealing),
        Index1Entity(context.getString(R.string.dog_sound_72), R.mipmap.ic_dog_grumpy_grumble, R.raw.dog_grumpy_grumble),
        Index1Entity(context.getString(R.string.dog_sound_73), R.mipmap.ic_dog_happy_bark, R.raw.dog_happy_bark),
        Index1Entity(context.getString(R.string.dog_sound_74), R.mipmap.ic_dog_happy_dance, R.raw.dog_happy_dance),
        Index1Entity(context.getString(R.string.dog_sound_75), R.mipmap.ic_dog_happy_wag, R.raw.dog_happy_wag),
        Index1Entity(context.getString(R.string.dog_sound_76), R.mipmap.ic_dog_hopeful_yelp, R.raw.dog_hopeful_yelp),
        Index1Entity(context.getString(R.string.dog_sound_77), R.mipmap.ic_dog_hungry_chew, R.raw.dog_hungry_chew),
        Index1Entity(context.getString(R.string.dog_sound_78), R.mipmap.ic_dog_jealous_hiss, R.raw.dog_jealous_hiss),
        Index1Entity(context.getString(R.string.dog_sound_79), R.mipmap.ic_dog_jovial_mumble, R.raw.dog_jovial_mumble),
        Index1Entity(context.getString(R.string.dog_sound_80), R.mipmap.ic_dog_jovial_squeal, R.raw.dog_jovial_squeal),
        Index1Entity(context.getString(R.string.dog_sound_81), R.mipmap.ic_dog_joyful_howl, R.raw.dog_joyful_howl),
        Index1Entity(context.getString(R.string.dog_sound_82), R.mipmap.ic_dog_jubilant_whinny, R.raw.dog_jubilant_whinny),
        Index1Entity(context.getString(R.string.dog_sound_83), R.mipmap.ic_dog_loving_hoot, R.raw.dog_loving_hoot),
        Index1Entity(context.getString(R.string.dog_sound_84), R.mipmap.ic_dog_loving_hooting, R.raw.dog_loving_hooting),
        Index1Entity(context.getString(R.string.dog_sound_85), R.mipmap.ic_dog_loving_snarl, R.raw.dog_loving_snarl),
        Index1Entity(context.getString(R.string.dog_sound_86), R.mipmap.ic_dog_loving_whimper, R.raw.dog_loving_whimper),
        Index1Entity(context.getString(R.string.dog_sound_87), R.mipmap.ic_dog_merry_trumpeting, R.raw.dog_merry_trumpeting),
        Index1Entity(context.getString(R.string.dog_sound_88), R.mipmap.ic_dog_mournful_sob, R.raw.dog_mournful_sob),
        Index1Entity(context.getString(R.string.dog_sound_89), R.mipmap.ic_dog_nervous_tremor, R.raw.dog_nervous_tremor),
        Index1Entity(context.getString(R.string.dog_sound_90), R.mipmap.ic_dog_overjoyed_purr, R.raw.dog_overjoyed_purr),
        Index1Entity(context.getString(R.string.dog_sound_91), R.mipmap.ic_dog_overjoyed_screech, R.raw.dog_overjoyed_screech),
        Index1Entity(context.getString(R.string.dog_sound_92), R.mipmap.ic_dog_overjoued_sniveling, R.raw.dog_overjoyed_sniveling),
        Index1Entity(context.getString(R.string.dog_sound_93), R.mipmap.ic_dog_peaceful_snarl, R.raw.dog_peaceful_snarl),
        Index1Entity(context.getString(R.string.dog_sound_94), R.mipmap.ic_dog_playful_bleat, R.raw.dog_playful_bleat),
        Index1Entity(context.getString(R.string.dog_sound_95), R.mipmap.ic_dog_playful_chirping, R.raw.dog_playful_chirping),
        Index1Entity(context.getString(R.string.dog_sound_96), R.mipmap.ic_dog_playful_hiss, R.raw.dog_playful_hiss),
        Index1Entity(context.getString(R.string.dog_sound_97), R.mipmap.ic_dog_playful_nudge, R.raw.dog_playful_nudge),
        Index1Entity(context.getString(R.string.dog_sound_98), R.mipmap.ic_dog_playful_squeak, R.raw.dog_playful_squeak),
        Index1Entity(context.getString(R.string.dog_sound_99), R.mipmap.ic_dog_playfule_yip, R.raw.dog_playful_yip),
        Index1Entity(context.getString(R.string.dog_sound_100), R.mipmap.ic_dog_pleased_hiss, R.raw.dog_pleased_hiss),
        Index1Entity(context.getString(R.string.dog_sound_101), R.mipmap.ic_dog_pleased_rumbling, R.raw.dog_pleased_rumbling),
        Index1Entity(context.getString(R.string.dog_sound_102), R.mipmap.ic_dog_relaxed_purr, R.raw.dog_relaxed_purr),
        Index1Entity(context.getString(R.string.dog_sound_103), R.mipmap.ic_dog_satisfied_grunt, R.raw.dog_satisfied_grunt),
        Index1Entity(context.getString(R.string.dog_sound_104), R.mipmap.ic_dog_sleepy_sigh, R.raw.dog_sleepy_sigh),
        Index1Entity(context.getString(R.string.dog_sound_105), R.mipmap.ic_dog_thankful_whistle, R.raw.dog_thankful_whistle),
        Index1Entity(context.getString(R.string.dog_sound_106), R.mipmap.ic_dog_thirsty_lap, R.raw.dog_thirsty_lap),
        Index1Entity(context.getString(R.string.dog_sound_107), R.mipmap.ic_dog_thrilled_braying, R.raw.dog_thrilled_braying),
        Index1Entity(context.getString(R.string.dog_sound_108), R.mipmap.ic_dog_trusting_whuff, R.raw.dog_trusting_whuff),
        Index1Entity(context.getString(R.string.dog_sound_109), R.mipmap.ic_dog_upbeat_whickering, R.raw.dog_upbeat_whickering),
    )

    fun catSoundList(context: Context) = listOf(
        Index1Entity(context.getString(R.string.cat_sound_1), R.mipmap.ic_cat_hello, R.raw.cat_hello),
        Index1Entity(context.getString(R.string.cat_sound_2), R.mipmap.ic_cat_i_love_u, R.raw.cat_i_love_you),
        Index1Entity(context.getString(R.string.cat_sound_3), R.mipmap.ic_cat_come_here, R.raw.cat_come_here),
        Index1Entity(context.getString(R.string.cat_sound_4), R.mipmap.ic_cat_hungry, R.raw.dog_hungry),
        Index1Entity(context.getString(R.string.cat_sound_5), R.mipmap.ic_cat_fine, R.raw.cat_fine),
        Index1Entity(context.getString(R.string.cat_sound_6), R.mipmap.ic_cat_angry, R.raw.dog_angry),
        Index1Entity(context.getString(R.string.cat_sound_7), R.mipmap.ic_cat_no_no, R.raw.cat_nono),
        Index1Entity(context.getString(R.string.cat_sound_8), R.mipmap.ic_cat_sad, R.raw.cat_nono),
        Index1Entity(context.getString(R.string.cat_sound_9), R.mipmap.ic_cat_fighting, R.raw.cat_should_not),
        Index1Entity(context.getString(R.string.cat_sound_10), R.mipmap.ic_cat_happy, R.raw.cat_yes),
        Index1Entity(context.getString(R.string.cat_sound_11), R.mipmap.ic_cat_tired, R.raw.cat_leave_me_alone),
        Index1Entity(context.getString(R.string.cat_sound_12), R.mipmap.ic_cat_sleep, R.raw.cat_come_here),
        Index1Entity(context.getString(R.string.cat_sound_13), R.mipmap.ic_cat_anxious_moan, R.raw.cat_anxious_moan),
        Index1Entity(context.getString(R.string.cat_sound_14), R.mipmap.ic_cat_bass_meow, R.raw.cat_bass_meow),
        Index1Entity(context.getString(R.string.cat_sound_15), R.mipmap.ic_cat_bossy_hiss, R.raw.cat_bossy_hiss),
        Index1Entity(context.getString(R.string.cat_sound_16), R.mipmap.ic_cat_bright_mew, R.raw.cat_bright_mew),
        Index1Entity(context.getString(R.string.cat_sound_17), R.mipmap.ic_cat_cheery_yowl, R.raw.cat_cheery_yowl),
        Index1Entity(context.getString(R.string.cat_sound_18), R.mipmap.ic_cat_croaky_chirp, R.raw.cat_croaky_chirp),
        Index1Entity(context.getString(R.string.cat_sound_19), R.mipmap.ic_cat_deep_purring, R.raw.cat_deep_purring),
        Index1Entity(context.getString(R.string.cat_sound_20), R.mipmap.ic_cat_defensive_hiss, R.raw.cat_defensive_hiss),
        Index1Entity(context.getString(R.string.cat_sound_21), R.mipmap.ic_cat_edgy_yowl, R.raw.cat_edgy_yowl),
        Index1Entity(context.getString(R.string.cat_sound_22), R.mipmap.ic_cat_excited_trill, R.raw.cat_excited_trill),
        Index1Entity(context.getString(R.string.cat_sound_23), R.mipmap.ic_cat_feeble_yowl, R.raw.cat_feeble_yowl),
        Index1Entity(context.getString(R.string.cat_sound_24), R.mipmap.ic_cat_fight_hiss, R.raw.cat_fight_hiss),
        Index1Entity(context.getString(R.string.cat_sound_25), R.mipmap.ic_cat_frail_moan, R.raw.cat_frail_moan),
        Index1Entity(context.getString(R.string.cat_sound_26), R.mipmap.ic_cat_friendly_meow, R.raw.cat_friendly_meow),
        Index1Entity(context.getString(R.string.cat_sound_27), R.mipmap.ic_cat_greating_meow, R.raw.cat_grating_meow),
        Index1Entity(context.getString(R.string.cat_sound_28), R.mipmap.ic_cat_growly_meow, R.raw.cat_growly_meow),
        Index1Entity(context.getString(R.string.cat_sound_29), R.mipmap.ic_cat_hateful_yowl, R.raw.cat_hateful_yowl),
        Index1Entity(context.getString(R.string.cat_sound_30), R.mipmap.ic_cat_high_mew, R.raw.cat_high_mew),
        Index1Entity(context.getString(R.string.cat_sound_31), R.mipmap.ic_cat_insistent_hiss, R.raw.cat_insistent_hiss),
        Index1Entity(context.getString(R.string.cat_sound_32), R.mipmap.ic_cat_kitten_mew, R.raw.cat_kitten_mew),
        Index1Entity(context.getString(R.string.cat_sound_33), R.mipmap.ic_cat_lilting_purr, R.raw.cat_lilting_purr),
        Index1Entity(context.getString(R.string.cat_sound_34), R.mipmap.ic_cat_long_grunt, R.raw.cat_long_grunt),
        Index1Entity(context.getString(R.string.cat_sound_35), R.mipmap.ic_cat_long_yowls, R.raw.cat_long_yowls),
        Index1Entity(context.getString(R.string.cat_sound_36), R.mipmap.ic_cat_lound_hiss, R.raw.cat_lound_hiss),
        Index1Entity(context.getString(R.string.cat_sound_37), R.mipmap.ic_cat_lovely_moan, R.raw.cat_lovely_moan),
        Index1Entity(context.getString(R.string.cat_sound_38), R.mipmap.ic_cat_low_purr, R.raw.cat_low_purr),
        Index1Entity(context.getString(R.string.cat_sound_39), R.mipmap.ic_cat_luscious_mew, R.raw.cat_luscious_mew),
        Index1Entity(context.getString(R.string.cat_sound_40), R.mipmap.ic_cat_mawkish_yowl, R.raw.cat_mawkish_yowl),
        Index1Entity(context.getString(R.string.cat_sound_41), R.mipmap.ic_cat_nasally_growl, R.raw.cat_nasally_growl),
        Index1Entity(context.getString(R.string.cat_sound_42), R.mipmap.ic_cat_orotund_meow, R.raw.cat_orotund_meow),
        Index1Entity(context.getString(R.string.cat_sound_43), R.mipmap.ic_cat_pain_meow, R.raw.cat_pain_meow),
        Index1Entity(context.getString(R.string.cat_sound_44), R.mipmap.ic_cat_petulant_yowl, R.raw.cat_petulant_yowl),
        Index1Entity(context.getString(R.string.cat_sound_45), R.mipmap.ic_cat_raspy_meow, R.raw.cat_raspy_meow),
        Index1Entity(context.getString(R.string.cat_sound_46), R.mipmap.ic_cat_scare_chirp, R.raw.cat_scare_chirp),
        Index1Entity(context.getString(R.string.cat_sound_47), R.mipmap.ic_cat_short_yowl, R.raw.cat_short_yowl),
        Index1Entity(context.getString(R.string.cat_sound_48), R.mipmap.ic_cat_shrill_meow, R.raw.cat_shrill_meow),
        Index1Entity(context.getString(R.string.cat_sound_49), R.mipmap.ic_cat_snarly_snarl, R.raw.cat_snarly_snarl),
        Index1Entity(context.getString(R.string.cat_sound_50), R.mipmap.ic_cat_snooty_meow, R.raw.cat_snooty_meow),
        Index1Entity(context.getString(R.string.cat_sound_51), R.mipmap.ic_cat_soft_chirp, R.raw.cat_soft_chirp),
        Index1Entity(context.getString(R.string.cat_sound_52), R.mipmap.ic_cat_soft_purr, R.raw.cat_soft_purr),
        Index1Entity(context.getString(R.string.cat_sound_53), R.mipmap.ic_cat_squeak_meow, R.raw.cat_squeak_meow),
        Index1Entity(context.getString(R.string.cat_sound_54), R.mipmap.ic_cat_stressed_purr, R.raw.cat_stressed_purr),
        Index1Entity(context.getString(R.string.cat_sound_55), R.mipmap.ic_cat_sullen_grunt, R.raw.cat_sullen_grunt),
        Index1Entity(context.getString(R.string.cat_sound_56), R.mipmap.ic_cat_sweet_meow, R.raw.cat_sweet_meow),
        Index1Entity(context.getString(R.string.cat_sound_57), R.mipmap.ic_cat_trembling_mew, R.raw.cat_trembling_mew),
        Index1Entity(context.getString(R.string.cat_sound_58), R.mipmap.ic_cat_upbeat_mew, R.raw.cat_upbeat_mew),
        Index1Entity(context.getString(R.string.cat_sound_59), R.mipmap.ic_cat_weak_mew, R.raw.cat_weak_mew),
        Index1Entity(context.getString(R.string.cat_sound_60), R.mipmap.ic_cat_weak_whine, R.raw.cat_weak_whine),
        Index1Entity(context.getString(R.string.cat_sound_61), R.mipmap.ic_cat_whiny_yowl, R.raw.cat_whiny_yowl),
    )


}